/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project_qlbh;

import DAO.DBConnect;
import java.awt.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.*;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.ui.RectangleInsets;

/**
 *
 * @author Administrator
 */
public class Bang_ThongKe_HocSinh extends javax.swing.JPanel {

    private DefaultPieDataset dataset = new DefaultPieDataset();
    private JFreeChart jfreeChart;
    private ChartPanel chartPanel;
    DefaultTableModel tblModelPL, tblModelHSX;

    /**
     * Creates new form ThongKeJPanel
     */
    public Bang_ThongKe_HocSinh() {
        initComponents();

        initTableLH();
        initTableHSX();
        LayDSLH();
       drawChartPieLopHoc();
        drawChartTreeKhoaHoc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThongKeHSX = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongKePL = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        pnlLopHoc = new javax.swing.JPanel();
        pnlKhoaHoc = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 51, 51));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblThongKeHSX.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane2.setViewportView(tblThongKeHSX);

        tblThongKePL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tblThongKePL);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("THỐNG KÊ SỐ LƯỢNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlLopHoc.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlLopHocLayout = new javax.swing.GroupLayout(pnlLopHoc);
        pnlLopHoc.setLayout(pnlLopHocLayout);
        pnlLopHocLayout.setHorizontalGroup(
            pnlLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlLopHocLayout.setVerticalGroup(
            pnlLopHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        pnlKhoaHoc.setBackground(new java.awt.Color(255, 255, 255));
        pnlKhoaHoc.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlKhoaHocLayout = new javax.swing.GroupLayout(pnlKhoaHoc);
        pnlKhoaHoc.setLayout(pnlKhoaHocLayout);
        pnlKhoaHocLayout.setHorizontalGroup(
            pnlKhoaHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
        pnlKhoaHocLayout.setVerticalGroup(
            pnlKhoaHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlKhoaHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLopHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlLopHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initTableLH() {
        tblModelPL = new DefaultTableModel();
        tblModelPL.setColumnIdentifiers(new String[]{"Lớp học", "Tổng số"});
        tblThongKePL.setModel(tblModelPL);
    }

    private void initTableHSX() {
        tblModelHSX = new DefaultTableModel();
        tblModelHSX.setColumnIdentifiers(new String[]{"Khóa học", "Tổng số"});
        tblThongKeHSX.setModel(tblModelHSX);
    }

    private void LayDSLH() {
        try {
            Connection conn = DBConnect.getConnection();
            String sql = "SELECT Lop_Hoc, SUM(Ma_HS) as sltungloai FROM Hoc_Sinh GROUP BY Lop_Hoc";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                String[] row = new String[]{
                    rs.getString("Lop_Hoc"), rs.getString("sltungloai")
                };
                tblModelPL.addRow(row);
            }
            tblModelPL.fireTableDataChanged();
      
            sql = "SELECT Khoa_Hoc, SUM(Ma_HS) as sltunghsx FROM Hoc_Sinh GROUP BY Khoa_Hoc";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()) {
                String[] row = new String[]{
                    rs.getString("Khoa_Hoc"), rs.getString("sltunghsx")
                };
                tblModelHSX.addRow(row);
            }
            tblModelHSX.fireTableDataChanged();

            rs.close();
            ps.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }

    private void drawChartPieLopHoc() {
        //Set gia tr cho PieChart
        String pl;
        int sl;
        for (int i = 0; i < tblThongKePL.getRowCount(); i++) {
            sl = Integer.parseInt(tblThongKePL.getValueAt(i, 1).toString());
            pl = tblThongKePL.getValueAt(i, 0).toString() + ": " + sl;
            dataset.setValue(pl, sl);
        }

        jfreeChart = ChartFactory.createPieChart3D("Thống kê lớp học", dataset, true, true, false);
        PiePlot3D plot = (PiePlot3D) jfreeChart.getPlot();
        plot.setForegroundAlpha(0.6f);
        plot.setBackgroundPaint(new Color(218, 0, 55)); //Set background cho PieChart
        jfreeChart.getTitle().setFont(new Font("Arial", Font.BOLD, 36));
        //panel Container chartPanel

        pnlLopHoc.setBackground(new Color(218, 0, 55));

        pnlLopHoc.setLayout(null);
        // add chartPanel PieChart vao panel
        chartPanel = new ChartPanel(jfreeChart);
        chartPanel.setBounds(175, 0, 500, 350); //set size PieChart
        pnlLopHoc.add(chartPanel);

        chartPanel.setMouseWheelEnabled(true);
        chartPanel.setZoomAroundAnchor(true);
        chartPanel.setBackground(SystemColor.menu);

    }

    private void drawChartTreeKhoaHoc() {
        String hsx;
        int sl;
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (int i = 0; i < tblThongKeHSX.getRowCount(); i++) {
            sl = Integer.parseInt(tblThongKeHSX.getValueAt(i, 1).toString());
            hsx = tblThongKeHSX.getValueAt(i, 0).toString() + ": " + sl;
            dataset.addValue(sl, "Học viên", hsx);
        }

        JFreeChart barChart = ChartFactory.createBarChart("Thống kê khóa học".toUpperCase(),
                "KHÓA HỌC", "Số lượng",
                dataset, PlotOrientation.VERTICAL, false, true, false);

        ChartPanel chartPanel = new ChartPanel(barChart);
        chartPanel.setPreferredSize(new Dimension(pnlKhoaHoc.getWidth(), 321));
        barChart.getPlot().setBackgroundPaint(Color.white);
        Paint p = new GradientPaint(0, 0, new Color(0, 2, 114), 1000, 0, Color.white);
        barChart.setBackgroundPaint(p);

        //pnlHSX.removeAll();
        pnlKhoaHoc.setLayout(new CardLayout());
        pnlKhoaHoc.add(chartPanel);
        pnlKhoaHoc.validate();
        pnlKhoaHoc.repaint();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlKhoaHoc;
    private javax.swing.JPanel pnlLopHoc;
    private javax.swing.JTable tblThongKeHSX;
    private javax.swing.JTable tblThongKePL;
    // End of variables declaration//GEN-END:variables
}
